version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: steam_postgres
    restart: always
    environment:
      POSTGRES_DB: steam_reviews
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data:
